version: "2"

services:
  ${PROJECT}_data_volume:
    image: 'debian'
    restart: 'always'
    container_name: ${PROJECT}_data_volume
    volumes:
      - ${PATH_TO_FILES}:/var/www/
    user: www-data
  ${PROJECT}_php:
    build: ./php
    volumes_from:
      - ${PROJECT}_data_volume:rw
    container_name: ${PROJECT}_php
    environment:
      XDEBUG_CONFIG: "remote_host=${HOST_IP} idekey=PHPSTORM"
  ${PROJECT}_cas-web:
    image: nginx:1.8.1
    ports:
      - "8050:8050"
    volumes_from:
      - ${PROJECT}_data_volume:rw
    volumes:
      - ./configs/cas.conf:/etc/nginx/conf.d/default.conf
    links:
      - ${PROJECT}_php
  ${PROJECT}_my-web:
    image: nginx:1.8.1
    ports:
      - "80:80"
    volumes_from:
      - ${PROJECT}_data_volume:rw
    volumes:
      - ./configs/my.conf:/etc/nginx/conf.d/default.conf
    links:
      - ${PROJECT}_php


