version: "2"

services:
  data_volume:
    image: 'debian'
    restart: 'always'
    container_name: ${PROJECT}data_volume
    volumes:
      - ${PATH_TO_FILES}:/var/www/
    user: www-data
  php:
    build: ./php
    image: ${PROJECT}php
    volumes_from:
      - data_volume:rw
    container_name: ${PROJECT}php
    links:
      - redis
      - mongo
    environment:
      XDEBUG_CONFIG: "remote_host=${HOST_IP} idekey=PHPSTORM"
  cas-web:
    image: nginx:1.8.1
    ports:
      - "8050:8050"
    volumes_from:
      - data_volume:rw
    volumes:
      - ./configs/cas.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  my-web:
    image: nginx:1.8.1
    ports:
      - "80:80"
    volumes_from:
      - data_volume:rw
    volumes:
      - ./configs/my.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  redis:
    image: redis:2
  mongo:
    image: mongo:2

    

