version: "2"

services:
  application_data_volume:
    image: 'debian'
    tty: true
    restart: 'always'
    container_name: 'application_data_volume'
    volumes:
      - '~/trash/cas-test/:/var/www/'
    user: www-data
  php:
    build: ./php
    volumes_from:
      - application_data_volume:rw
    container_name: 'my-php'
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.60.117 idekey=PHPSTORM"
    user: www-data
  cas-web:
    image: nginx:1.8.1
    ports:
      - "8050:8050"
    volumes_from:
      - php
    volumes:
      - ./configs/cas.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  my-web:
    image: nginx:1.8.1
    ports:
      - "80:80"
    volumes_from:
      - php
    volumes:
      - ./configs/my.conf:/etc/nginx/conf.d/default.conf
    links:
      - php


